### ISSUE TITLE
‘TypeError: NetworkError when attempting to fetch resource’

### ISSUE THREAD

**Issue by bradrn** [defseg/pshrimp-server#4]
(I’m actually not quite sure where to post this issue; for now I think it’s a problem with the server, but feel free to tell me if this is the wrong repo.)

I regularly use [Pshrimp](https://defseg.io/pshrimp-client) to find languages with specific phonological properties. However, over the past few days, every search I try has returned the same error, making Pshrimp unusable:

> TypeError: NetworkError when attempting to fetch resource.

The JavaScript console reveals more details:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pshrimp.herokuapp.com/query/%2Fp%2F. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

(That message was for a search `/p/`, but of course it changes with the search string.)

Furthermore, when I try to manually query the API request given in the message above, I get the following response:

> ### Application error
>
> An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command `heroku logs --tail`

**Comment by defseg** [comment]
This is the right repo - if sending queries directly to the site (as in the link above) doesn't work, there's a server error. But it doesn't matter _too_ much where things go.

Heroku started requiring SSL for postgres connections, so the server couldn't connect to the database. I just pushed a fix (commit #182) - let me know if anything doesn't work.

**Comment by bradrn** [comment]
Thanks @defseg! Looks like it’s working now.
